"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { SECTION_META } from "@/lib/constants/sections";
import type { SectionType } from "@/lib/constants/sections";

interface WorkspaceData {
  name: string;
  idea: string;
  industry?: string | null;
  startupStage?: string | null;
  createdAt: string;
  sections: {
    type: string;
    content: string | null;
    generationStatus: string;
  }[];
}

/**
 * Score a section based on content quality (word count, structure).
 * Returns a score out of 10.
 */
function scoreSection(content: string | null): number {
  if (!content) return 0;
  const wordCount = content.split(/\s+/).length;
  const hasHeadings = (content.match(/^#{1,3}\s/gm) || []).length;
  const hasLists = (content.match(/^[-*]\s/gm) || []).length;
  const hasTables = content.includes("|");

  let score = 0;
  // Word count scoring (max 4 points)
  if (wordCount > 500) score += 4;
  else if (wordCount > 300) score += 3;
  else if (wordCount > 150) score += 2;
  else if (wordCount > 50) score += 1;

  // Structure scoring (max 3 points)
  if (hasHeadings >= 4) score += 3;
  else if (hasHeadings >= 2) score += 2;
  else if (hasHeadings >= 1) score += 1;

  // Detail scoring (max 3 points)
  if (hasLists >= 5) score += 2;
  else if (hasLists >= 2) score += 1;
  if (hasTables) score += 1;

  return Math.min(10, score);
}

/**
 * Strip markdown formatting for plain text output in PDF.
 */
function stripMarkdown(text: string): string {
  return text
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`(.*?)`/g, "$1")
    .replace(/^[-*]\s+/gm, "• ")
    .replace(/^\d+\.\s+/gm, "  ")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^---$/gm, "")
    .trim();
}

export function generatePDFReport(workspace: WorkspaceData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const blueprintSections = workspace.sections.filter(
    (s) =>
      s.type !== "ai-chat" && s.type !== "files" && s.type !== "settings",
  );

  // -- Cover Page --
  doc.setFillColor(15, 15, 20);
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  doc.text(workspace.name, pageWidth / 2, 60, { align: "center" });

  // Subtitle
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 160, 180);
  doc.text("Startup Blueprint Report", pageWidth / 2, 75, { align: "center" });

  // Idea
  doc.setFontSize(10);
  doc.setTextColor(140, 140, 160);
  const ideaLines = doc.splitTextToSize(workspace.idea, contentWidth - 20);
  doc.text(ideaLines, pageWidth / 2, 95, { align: "center" });

  // Metadata
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 140);
  const meta = [];
  if (workspace.industry) meta.push(`Industry: ${workspace.industry}`);
  if (workspace.startupStage) meta.push(`Stage: ${workspace.startupStage}`);
  meta.push(`Generated: ${new Date().toLocaleDateString()}`);
  doc.text(meta.join("  |  "), pageWidth / 2, 120, { align: "center" });

  // Score summary on cover
  const scores = blueprintSections.map((s) => ({
    type: s.type,
    score: scoreSection(s.content),
  }));
  const avgScore =
    scores.reduce((sum, s) => sum + s.score, 0) / scores.length;

  doc.setFontSize(48);
  doc.setTextColor(99, 102, 241); // Indigo
  doc.setFont("helvetica", "bold");
  doc.text(`${avgScore.toFixed(1)}`, pageWidth / 2, 160, { align: "center" });
  doc.setFontSize(12);
  doc.setTextColor(160, 160, 180);
  doc.text("Overall Blueprint Score / 10", pageWidth / 2, 172, {
    align: "center",
  });

  // Score breakdown table on cover
  const completedCount = blueprintSections.filter(
    (s) => s.generationStatus === "completed",
  ).length;
  doc.setFontSize(10);
  doc.setTextColor(140, 140, 160);
  doc.text(
    `${completedCount} / ${blueprintSections.length} sections generated`,
    pageWidth / 2,
    185,
    { align: "center" },
  );

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(80, 80, 100);
  doc.text(
    "Generated by FounderOS AI — founderos.ai",
    pageWidth / 2,
    275,
    { align: "center" },
  );

  // -- Scorecard Page --
  doc.addPage();
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), "F");

  doc.setTextColor(20, 20, 30);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Blueprint Scorecard", margin, 30);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 120);
  doc.text(
    "Each section is scored based on content depth, structure, and completeness.",
    margin,
    40,
  );

  // Score table
  const tableData = scores.map((s) => {
    const meta = SECTION_META[s.type as SectionType];
    const label = meta?.label || s.type;
    const bar = "█".repeat(s.score) + "░".repeat(10 - s.score);
    return [label, bar, `${s.score}/10`];
  });

  tableData.push(["", "", ""]);
  tableData.push(["OVERALL SCORE", "", `${avgScore.toFixed(1)}/10`]);

  autoTable(doc, {
    startY: 50,
    head: [["Section", "Score", "Rating"]],
    body: tableData,
    margin: { left: margin, right: margin },
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: {
      fillColor: [99, 102, 241],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: [248, 248, 252] },
  });

  // -- Content Pages --
  for (const section of blueprintSections) {
    if (!section.content || section.generationStatus !== "completed") continue;

    doc.addPage();
    y = margin;

    const meta = SECTION_META[section.type as SectionType];
    const label = meta?.label || section.type;
    const score = scoreSection(section.content);

    // Section header
    doc.setFillColor(248, 248, 252);
    doc.rect(0, 0, pageWidth, 45, "F");

    doc.setTextColor(20, 20, 30);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(label, margin, 20);

    doc.setFontSize(9);
    doc.setTextColor(100, 100, 120);
    doc.setFont("helvetica", "normal");
    doc.text(meta?.description || "", margin, 28);

    // Score badge
    doc.setFillColor(99, 102, 241);
    doc.roundedRect(pageWidth - margin - 25, 12, 25, 12, 3, 3, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(`${score}/10`, pageWidth - margin - 12.5, 20, { align: "center" });

    // Content
    y = 50;
    doc.setTextColor(40, 40, 50);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");

    const plainText = stripMarkdown(section.content);
    const lines = doc.splitTextToSize(plainText, contentWidth);

    for (const line of lines) {
      if (y > 270) {
        doc.addPage();
        y = margin;
      }
      // Bold lines that look like headings
      if (line.length < 60 && line === line.toUpperCase() && line.length > 3) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        y += 3;
      } else if (line.startsWith("•")) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
      } else {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
      }
      doc.text(line, margin, y);
      y += 4.5;
    }
  }

  // Save
  const filename = `${workspace.name.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}-blueprint.pdf`;
  doc.save(filename);
}
